package org.jbc;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chanelj' at '03.02.17 10:36' with Gradle 2.13
 *
 * @author chanelj, @date 03.02.17 10:36
 */
public class Library {
  public boolean someLibraryMethod() {
    return true;
  }

}
